
//23.Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test.
//  Your code should look something like this:

// • Look closely at your results, and make sure you understand why each line evaluates to True or False.

// • Create at least 10 tests. Have at least 5 tests evaluate to True and another 5 tests evaluate to False.

let car  = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car =='subaru');

console.log("Is car == 'honda'? I predict False.");

console.log(car=='honda' );

//Evaluate to true
let Name = 'waqar';
console.log("Is name == 'waqar'? I predict true");
console.log(Name == 'waqar');

let student = 'waqar';
console.log("Is student == 'waqar' I predict true");
console.log(student == 'waqar');

let waqar = 'programer'
console.log("Is waqar == 'programer'? I predict true ");
console.log(waqar== 'programer');
 
let school = 'Student';
console.log("Is school == 'student'? I predict true");
console.log(school== 'Student');

let oldmen = 87
console.log('Is odlmen ==  87? I predict true');
console.log(oldmen==87);

//Evaluate to false
let laptop = 'machine';
console.log("Is laptop == 'machine'? I predict false");
console.log(laptop == 'Machine');
 
let  city = 'Lahore';
console.log('Is city == lahore? I predict False');
console.log(city== 'country');

let  country = 'Pakistan';
console.log('Is country == pakistan? I predict False');
console.log(country== 'pakistan');
 
let sellphone = 'iphone';
console.log('Is sellphone == Iphone? I predict False');
console.log(sellphone=='Iphone');

let apple = 'Fruit';
console.log('Is apple== fruit? I predict False');
console.log(apple=='fruit');
